stages:
  - build
  - report

frontend:
  stage: build
  trigger:
    include: code/frontend/.gitlab-ci.yml
    strategy: depend

backend:
  stage: build
  trigger:
    include: code/backend/.gitlab-ci.yml
    strategy: depend

cli:
  stage: build
  trigger:
    include: code/client/.gitlab-ci.yml
    strategy: depend

report-frontend:
  stage: report
  dependencies:
    - frontend
  script:
    - echo "Frontend Coverage Report"
    - cat code/frontend/coverage/coverage-final.json
  cache:
    - key: "$CI_COMMIT_REF_SLUG-reports"
    paths:
      - code/frontend/coverage/coverage-final.json
      - code/frontend/coverage/junit.xml
    policy: pull
  coverage: /All files\s*\|\s*([\d.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: code/frontend/coverage/coverage-final.json
      junit: code/frontend/coverage/junit.xml
