frontend:
  trigger:
    include: code/frontend/.gitlab-ci.yml
    strategy: depend

backend:
  trigger:
    include: code/backend/.gitlab-ci.yml
    strategy: depend

cli:
  trigger:
    include: code/client/.gitlab-ci.yml
    strategy: depend
