image: node:22.13.0

stages:
  - lint
  - build
  - test

cache:
  key: frontend-cache
  paths:
    - code/frontend/node_modules/

before_script:
  - cd code/frontend
  - npm install

lint:
  stage: lint
  script:
    - npm run lint
  
build:
  stage: build
  script:
    - npm run build
    - test -d dist
    - test -f dist/index.html

.test:
  stage: test
  script:
    - npm run test
