image: node:23.6.0

stages:
  - lint
  - build
  - test

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest

cache:
  key: frontend-cache
  paths:
    - node_modules/

before_script:
  - cd code/frontend
  - npm install

lint:
  stage: lint
  rules:
    - changes:
      - code/frontend/**/*
      - code/frontend/.gitlab-ci.yml
      - .gitlab-ci.yml
  script:
    - npm run lint
  
build:
  stage: build
  rules:
    - changes:
      - code/frontend/**/*
      - code/frontend/.gitlab-ci.yml
      - .gitlab-ci.yml
  script:
    - npm run build
    - test -d dist
    - test -f dist/index.html

test:
  stage: test
  rules:
    - changes:
      - code/frontend/**/*
      - code/frontend/.gitlab-ci.yml
      - code/backend/**/*
      - .gitlab-ci.yml
  script:
    - npm run test