image: node:22.13.0

stages:
  - lint
  - build
  - test

cache:
  key: frontend-cache
  paths:
    - code/frontend/node_modules/

before_script:
  - cd code/frontend
  - npm install

lint:
  stage: lint
  script:
    - npm run lint
  
build:
  stage: build
  script:
    - npm run build
    - test -d dist
    - test -f dist/index.html

test:
  stage: test
  coverage: /All files\s*\|\s*([\d.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  script:
    - npm run test
    - npm run coverage
