image: node:23.6.0

stages:
  - lint
  - test

cache:
  key: backend-cache
  paths:
    - code/backend/node_modules/

before_script:
  - cd code/backend
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

.test:
  stage: test
  coverage: /All files\s*\|\s*([\d.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  script:
    - npm run coverage:c8
