image: node:23.6.0

stages:
  - lint
  - test

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest

cache:
  key: backend-cache
  paths:
    - node_modules/

before_script:
  - cd code/backend
  - npm install

lint:
  stage: lint
  rules:
    - changes:
      - code/backend/**/*
      - code/backend/.gitlab-ci.yml
      - .gitlab-ci.yml
  script:
    - npm run lint

test:
  stage: test
  rules:
    - changes:
      - code/backend/**/*
      - code/backend/.gitlab-ci.yml
      - .gitlab-ci.yml
  script:
    - npm run test