image: golang:1.23.1

stages:
  - lint
  - build
  - test

cache:
  key: gocache
  paths:
    - go/pkg/mod/
    - go/bin/
    - go/cache/
    - go/linter-cache/

variables:
  GOCACHE: ${CI_PROJECT_DIR}/go/cache
  GOPATH: ${CI_PROJECT_DIR}/go
  GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/go/linter-cache

before_script:
  - cd code/client
  - mkdir -p "${GOPATH}/bin"
  - mkdir -p "${GOCACHE}"
  - go mod download
  - go mod tidy

lint:
  stage: lint
  image: golangci/golangci-lint:latest-alpine
  script:
    - golangci-lint run --timeout=5m
    - go fmt ./...
    - go vet ./...

build:
  stage: build
  script: 
    - make build
    - test -x noted

.test:
  stage: test
  script:
    - make test
